apiVersion: batch/v1
kind: Job
metadata:
  name: run-migrations
  namespace: backend
spec:
  template:
    spec:
      serviceAccountName: backend-sa
      containers:
      - name: migrate
        image: cost-backend:day22
        command: ["alembic", "upgrade", "head"]
        envFrom:
        - configMapRef:
            name: cost-platform-config
        - secretRef:
            name: cost-platform-secrets
      restartPolicy: Never
  backoffLimit: 2
