"""add cloud resources and cost records tables

Revision ID: 5b1ef4bca4d1
Revises: ec8f5e798c39
Create Date: 2026-06-29 20:38:05.727088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b1ef4bca4d1'
down_revision: Union[str, Sequence[str], None] = 'ec8f5e798c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
